events { 
    worker_connections 1024; 
}

http {
    # Otimizações de performance
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Configurações padrão de Proxy (Headers fundamentais para Microsserviços)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 1. Frontend Angular
        location / {
            proxy_pass http://frontend:4200/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 2. Microsserviço de Auth (Porta 8081)
        # Nota: O /auth/ no final coincide com o context-path do application.yml
        location /api/auth/ {
            proxy_pass http://ms-auth:8081/auth/;
        }

        # 3. Microsserviço de Cliente (Porta 8082)
        location /api/clientes/ {
            proxy_pass http://ms-cliente:8082/clientes/;
        }

        # 4. Microsserviço de Conta (Porta 8083)
        location /api/contas/ {
            proxy_pass http://ms-conta:8083/contas/;
        }

        # 5. Microsserviço de Gerente (Porta 8084)
        location /api/gerentes/ {
            proxy_pass http://ms-gerente:8084/gerentes/;
        }

        # 6. Microsserviço Saga Orchestrator (Porta 8085)
        # Responsável pelo Autocadastro e Aprovação
        location /api/saga/ {
            proxy_pass http://ms-saga:8085/saga/;
        }

        # Tratamento de Erro Global para o Gateway
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}