server:
  port: 8082
  servlet:
    context-path: /clientes

spring:
  application:
    name: ms-cliente
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cliente_db}
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info

bantads:
  saga:
    exchange: bantads.saga
    routing-key-pendente-criado: evt.cliente.pendente.criado
    routing-key-aprovacao-iniciada: evt.cliente.aprovacao.iniciada
    routing-key-rejeitado: evt.cliente.rejeitado
